### ISSUE TITLE
请检查是否正确

### ISSUE THREAD

**Issue by eaglexpf** [hyperf/utils#7]
在这个文件ChannelClosedException.php中
```
namespace Hyperf\Utils\Exception;

class_alias(\Hyperf\Coroutine\Exception\ChannelClosedException::class, ChannelClosedException::class);

if (! class_exists(ChannelClosedException::class)) {
    /**
     * @deprecated since 3.1, use Hyperf\Coroutine\Exception\ChannelClosedException instead.
     */
    class ChannelClosedException extends \Hyperf\Coroutine\Exception\ChannelClosedException
    {
    }
}
```

继承了一个不存在的类

**Comment by limingxinleo** [comment]
正确的

**Comment by eaglexpf** [comment]
创建hyperf项目
```
/app/hyperf-skeleton # php bin/hyperf.php start
PHP Warning:  Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 14

Warning: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 14
PHP Fatal error:  Uncaught Error: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php:20
Stack trace:
#0 /app/hyperf-skeleton/vendor/composer/ClassLoader.php(582): include()
#1 /app/hyperf-skeleton/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /app/hyperf-skeleton/vendor/hyperf/utils/src/Functions.php(541): class_exists()
#4 /app/hyperf-skeleton/vendor/composer/autoload_real.php(41): require('...')
#5 /app/hyperf-skeleton/vendor/composer/autoload_real.php(45): {closure}()
#6 /app/hyperf-skeleton/vendor/autoload.php(25): ComposerAutoloaderInitb644887e3f3606eddc129ea5962a5fa2::getLoader()
#7 /app/hyperf-skeleton/bin/hyperf.php(20): require('...')
#8 {main}
  thrown in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 20

Fatal error: Uncaught Error: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php:20
Stack trace:
#0 /app/hyperf-skeleton/vendor/composer/ClassLoader.php(582): include()
#1 /app/hyperf-skeleton/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /app/hyperf-skeleton/vendor/hyperf/utils/src/Functions.php(541): class_exists()
#4 /app/hyperf-skeleton/vendor/composer/autoload_real.php(41): require('...')
#5 /app/hyperf-skeleton/vendor/composer/autoload_real.php(45): {closure}()
#6 /app/hyperf-skeleton/vendor/autoload.php(25): ComposerAutoloaderInitb644887e3f3606eddc129ea5962a5fa2::getLoader()
#7 /app/hyperf-skeleton/bin/hyperf.php(20): require('...')
#8 {main}
  thrown in /app/hyperf-skeleton/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 20
```
